#!/usr/bin/env bash
#
# GitKeeper - configure command
# Interactive configuration wizard
#

# Available rules with descriptions
declare -A RULE_DESCRIPTIONS=(
    [secrets]="Detect leaked API keys, tokens, and passwords"
    [forbid_files]="Block sensitive files (.env, private keys, credentials)"
    [changelog]="Require CHANGELOG updates with code changes"
    [version]="Track version file updates"
    [readme]="Verify README exists in repository"
    [todos]="Warn on new TODO/FIXME comments"
    [branch_name]="Enforce branch naming conventions"
    [large_files]="Prevent large files from being committed"
    [merge_conflict]="Detect leftover merge conflict markers"
)

RULE_ORDER=(secrets forbid_files merge_conflict large_files changelog version readme todos branch_name)

#------------------------------------------------------------------------------
# Menu helpers
#------------------------------------------------------------------------------

clear_screen() {
    # Only clear if interactive
    [[ -t 1 ]] && clear
}

print_header() {
    echo ""
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  $1${NC}"
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

print_menu_item() {
    local num="$1"
    local label="$2"
    local value="${3:-}"
    
    if [[ -n "$value" ]]; then
        echo -e "  ${CYAN}[$num]${NC} $label: ${DIM}$value${NC}"
    else
        echo -e "  ${CYAN}[$num]${NC} $label"
    fi
}

print_toggle() {
    local num="$1"
    local label="$2"
    local enabled="$3"
    
    if [[ "$enabled" == "1" || "$enabled" == "true" ]]; then
        echo -e "  ${CYAN}[$num]${NC} ${GREEN}●${NC} $label"
    else
        echo -e "  ${CYAN}[$num]${NC} ${DIM}○${NC} $label"
    fi
}

read_choice() {
    local prompt="${1:-Choice}"
    local input
    echo ""
    echo -en "${BOLD}$prompt:${NC} "
    read -r input
    REPLY="$input"
}

read_input() {
    local prompt="$1"
    local default="${2:-}"
    local input
    
    echo ""
    if [[ -n "$default" ]]; then
        echo -en "${BOLD}$prompt${NC} [${DIM}$default${NC}]: "
    else
        echo -en "${BOLD}$prompt${NC}: "
    fi
    read -r input
    REPLY="${input:-$default}"
}

press_enter() {
    echo ""
    echo -en "${DIM}Press Enter to continue...${NC}"
    read -r
}

#------------------------------------------------------------------------------
# Configuration state
#------------------------------------------------------------------------------

declare -A CONFIG_VALUES=()
CONFIG_FILE=""
CONFIG_MODIFIED=0

load_config() {
    local file="$1"
    CONFIG_FILE="$file"
    
    # Set defaults
    CONFIG_VALUES[rules]="secrets,forbid_files,merge_conflict,large_files"
    CONFIG_VALUES[fail_on]="error"
    CONFIG_VALUES[check_stash]="0"
    CONFIG_VALUES[stash_fail_on]="warn"
    
    if [[ ! -f "$file" ]]; then
        return 0
    fi
    
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
        [[ "$key" =~ ^[[:space:]]*# ]] && continue
        [[ -z "$key" ]] && continue
        
        key="$(echo "$key" | xargs)"
        value="$(echo "$value" | sed 's/#.*$//' | xargs)"
        
        CONFIG_VALUES["$key"]="$value"
    done < "$file"
}

save_config() {
    local file="$1"
    
    cat > "$file" << EOF
# GitKeeper Configuration
# Generated by: gitkeeper configure
# $(date)

# ─────────────────────────────────────────────────────────────────────────────
# Rules
# ─────────────────────────────────────────────────────────────────────────────

rules=${CONFIG_VALUES[rules]}

# ─────────────────────────────────────────────────────────────────────────────
# Behavior
# ─────────────────────────────────────────────────────────────────────────────

fail_on=${CONFIG_VALUES[fail_on]}
check_stash=${CONFIG_VALUES[check_stash]}
stash_fail_on=${CONFIG_VALUES[stash_fail_on]}

# ─────────────────────────────────────────────────────────────────────────────
# Rule Parameters
# ─────────────────────────────────────────────────────────────────────────────
EOF

    # Add custom patterns
    for key in "${!CONFIG_VALUES[@]}"; do
        case "$key" in
            pattern_*|trigger_*|required_*)
                echo "" >> "$file"
                echo "$key=${CONFIG_VALUES[$key]}" >> "$file"
                ;;
        esac
    done
    
    CONFIG_MODIFIED=0
    log_success "Saved to $file"
}

is_rule_enabled() {
    local rule="$1"
    local rules="${CONFIG_VALUES[rules]}"
    [[ ",$rules," == *",$rule,"* ]]
}

toggle_rule() {
    local rule="$1"
    local rules="${CONFIG_VALUES[rules]}"
    
    if is_rule_enabled "$rule"; then
        # Remove rule
        rules="$(echo "$rules" | sed "s/,$rule,/,/g; s/^$rule,//; s/,$rule$//; s/^$rule$//")"
    else
        # Add rule
        if [[ -z "$rules" ]]; then
            rules="$rule"
        else
            rules="$rules,$rule"
        fi
    fi
    
    CONFIG_VALUES[rules]="$rules"
    CONFIG_MODIFIED=1
}

#------------------------------------------------------------------------------
# Menu screens
#------------------------------------------------------------------------------

menu_main() {
    while true; do
        clear_screen
        print_header "GitKeeper Configuration"
        
        echo -e "  Config: ${CYAN}${CONFIG_FILE:-<not set>}${NC}"
        [[ $CONFIG_MODIFIED -eq 1 ]] && echo -e "  ${YELLOW}(unsaved changes)${NC}"
        echo ""
        
        print_menu_item "1" "Rules" "$(echo "${CONFIG_VALUES[rules]}" | tr ',' ' ' | wc -w | xargs) enabled"
        print_menu_item "2" "Behavior" "fail on ${CONFIG_VALUES[fail_on]}"
        print_menu_item "3" "Rule parameters" "patterns & triggers"
        echo ""
        print_menu_item "s" "Save configuration"
        print_menu_item "q" "Quit"
        
        read_choice
        
        case "$REPLY" in
            1) menu_rules ;;
            2) menu_behavior ;;
            3) menu_parameters ;;
            s|S)
                save_config "$CONFIG_FILE"
                press_enter
                ;;
            q|Q)
                if [[ $CONFIG_MODIFIED -eq 1 ]]; then
                    echo ""
                    echo -en "${YELLOW}Unsaved changes. Save before quitting?${NC} [Y/n] "
                    read -r yn
                    if [[ "${yn,,}" != "n" ]]; then
                        save_config "$CONFIG_FILE"
                    fi
                fi
                return 0
                ;;
        esac
    done
}

menu_rules() {
    while true; do
        clear_screen
        print_header "Enable/Disable Rules"
        
        echo "  Toggle rules on/off by entering their number."
        echo ""
        
        local i=1
        for rule in "${RULE_ORDER[@]}"; do
            local enabled=0
            is_rule_enabled "$rule" && enabled=1
            
            local desc="${RULE_DESCRIPTIONS[$rule]:-}"
            if [[ $enabled -eq 1 ]]; then
                echo -e "  ${CYAN}[$i]${NC} ${GREEN}●${NC} ${BOLD}$rule${NC}"
            else
                echo -e "  ${CYAN}[$i]${NC} ${DIM}○${NC} $rule"
            fi
            echo -e "      ${DIM}$desc${NC}"
            echo ""
            ((i++))
        done
        
        print_menu_item "a" "Enable all"
        print_menu_item "n" "Disable all"
        print_menu_item "b" "Back"
        
        read_choice
        
        case "$REPLY" in
            [1-9])
                local idx=$((REPLY - 1))
                if [[ $idx -lt ${#RULE_ORDER[@]} ]]; then
                    toggle_rule "${RULE_ORDER[$idx]}"
                fi
                ;;
            a|A)
                CONFIG_VALUES[rules]="$(IFS=','; echo "${RULE_ORDER[*]}")"
                CONFIG_MODIFIED=1
                ;;
            n|N)
                CONFIG_VALUES[rules]=""
                CONFIG_MODIFIED=1
                ;;
            b|B)
                return 0
                ;;
        esac
    done
}

menu_behavior() {
    while true; do
        clear_screen
        print_header "Behavior Settings"
        
        # fail_on
        echo -e "  ${BOLD}When to fail:${NC}"
        if [[ "${CONFIG_VALUES[fail_on]}" == "error" ]]; then
            echo -e "  ${CYAN}[1]${NC} ${GREEN}●${NC} error  ${DIM}— only fail on errors${NC}"
            echo -e "  ${CYAN}[2]${NC} ${DIM}○${NC} warn   ${DIM}— also fail on warnings${NC}"
        else
            echo -e "  ${CYAN}[1]${NC} ${DIM}○${NC} error  ${DIM}— only fail on errors${NC}"
            echo -e "  ${CYAN}[2]${NC} ${GREEN}●${NC} warn   ${DIM}— also fail on warnings${NC}"
        fi
        echo ""
        
        # check_stash
        echo -e "  ${BOLD}Stash checking:${NC}"
        print_toggle "3" "Check stash contents" "${CONFIG_VALUES[check_stash]}"
        echo ""
        
        if [[ "${CONFIG_VALUES[check_stash]}" == "1" ]]; then
            echo -e "  ${BOLD}Stash fail on:${NC}"
            if [[ "${CONFIG_VALUES[stash_fail_on]}" == "warn" ]]; then
                echo -e "  ${CYAN}[4]${NC} ${GREEN}●${NC} warn   ${DIM}— warn on stash issues${NC}"
                echo -e "  ${CYAN}[5]${NC} ${DIM}○${NC} error  ${DIM}— fail on stash issues${NC}"
            else
                echo -e "  ${CYAN}[4]${NC} ${DIM}○${NC} warn   ${DIM}— warn on stash issues${NC}"
                echo -e "  ${CYAN}[5]${NC} ${GREEN}●${NC} error  ${DIM}— fail on stash issues${NC}"
            fi
            echo ""
        fi
        
        print_menu_item "b" "Back"
        
        read_choice
        
        case "$REPLY" in
            1)
                CONFIG_VALUES[fail_on]="error"
                CONFIG_MODIFIED=1
                ;;
            2)
                CONFIG_VALUES[fail_on]="warn"
                CONFIG_MODIFIED=1
                ;;
            3)
                if [[ "${CONFIG_VALUES[check_stash]}" == "1" ]]; then
                    CONFIG_VALUES[check_stash]="0"
                else
                    CONFIG_VALUES[check_stash]="1"
                fi
                CONFIG_MODIFIED=1
                ;;
            4)
                CONFIG_VALUES[stash_fail_on]="warn"
                CONFIG_MODIFIED=1
                ;;
            5)
                CONFIG_VALUES[stash_fail_on]="error"
                CONFIG_MODIFIED=1
                ;;
            b|B)
                return 0
                ;;
        esac
    done
}

menu_parameters() {
    while true; do
        clear_screen
        print_header "Rule Parameters"
        
        echo "  Custom patterns and settings for rules."
        echo ""
        
        print_menu_item "1" "Secret patterns" "${CONFIG_VALUES[pattern_secrets]:-<default>}"
        print_menu_item "2" "Forbidden file patterns" "${CONFIG_VALUES[pattern_forbid_files]:-<default>}"
        print_menu_item "3" "Branch name pattern" "${CONFIG_VALUES[pattern_branch_name]:-<default>}"
        print_menu_item "4" "Max file size" "${CONFIG_VALUES[pattern_large_files]:-5MB}"
        print_menu_item "5" "Changelog triggers" "${CONFIG_VALUES[trigger_changelog]:-<default>}"
        print_menu_item "6" "Version files" "${CONFIG_VALUES[required_version]:-<default>}"
        echo ""
        print_menu_item "b" "Back"
        
        read_choice
        
        case "$REPLY" in
            1)
                echo ""
                echo -e "${DIM}Enter comma-separated regex patterns for secrets${NC}"
                echo -e "${DIM}Example: MY_API_[A-Z0-9]+,CUSTOM_KEY_[a-z]+${NC}"
                read_input "Patterns" "${CONFIG_VALUES[pattern_secrets]:-}"
                if [[ -n "$REPLY" ]]; then
                    CONFIG_VALUES[pattern_secrets]="$REPLY"
                    CONFIG_MODIFIED=1
                fi
                ;;
            2)
                echo ""
                echo -e "${DIM}Enter comma-separated regex patterns for forbidden files${NC}"
                echo -e "${DIM}Example: \\.secret$,private/.*${NC}"
                read_input "Patterns" "${CONFIG_VALUES[pattern_forbid_files]:-}"
                if [[ -n "$REPLY" ]]; then
                    CONFIG_VALUES[pattern_forbid_files]="$REPLY"
                    CONFIG_MODIFIED=1
                fi
                ;;
            3)
                echo ""
                echo -e "${DIM}Enter regex pattern for branch names${NC}"
                echo -e "${DIM}Example: ^(feature|bugfix|hotfix)/[a-z0-9-]+$${NC}"
                read_input "Pattern" "${CONFIG_VALUES[pattern_branch_name]:-}"
                if [[ -n "$REPLY" ]]; then
                    CONFIG_VALUES[pattern_branch_name]="$REPLY"
                    CONFIG_MODIFIED=1
                fi
                ;;
            4)
                echo ""
                echo -e "${DIM}Enter max file size in bytes (default: 5242880 = 5MB)${NC}"
                read_input "Size in bytes" "${CONFIG_VALUES[pattern_large_files]:-5242880}"
                if [[ -n "$REPLY" ]]; then
                    CONFIG_VALUES[pattern_large_files]="$REPLY"
                    CONFIG_MODIFIED=1
                fi
                ;;
            5)
                echo ""
                echo -e "${DIM}Enter regex for files that require changelog update${NC}"
                echo -e "${DIM}Example: \\.(js|ts|py|go)$${NC}"
                read_input "Pattern" "${CONFIG_VALUES[trigger_changelog]:-}"
                if [[ -n "$REPLY" ]]; then
                    CONFIG_VALUES[trigger_changelog]="$REPLY"
                    CONFIG_MODIFIED=1
                fi
                ;;
            6)
                echo ""
                echo -e "${DIM}Enter comma-separated version file names${NC}"
                echo -e "${DIM}Example: package.json,VERSION,setup.py${NC}"
                read_input "Files" "${CONFIG_VALUES[required_version]:-}"
                if [[ -n "$REPLY" ]]; then
                    CONFIG_VALUES[required_version]="$REPLY"
                    CONFIG_MODIFIED=1
                fi
                ;;
            b|B)
                return 0
                ;;
        esac
    done
}

#------------------------------------------------------------------------------
# Command entry point
#------------------------------------------------------------------------------

cmd_configure() {
    local config_file=".gitkeeper.conf"
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --config)
                config_file="$2"
                shift 2
                ;;
            --config=*)
                config_file="${1#--config=}"
                shift
                ;;
            *)
                shift
                ;;
        esac
    done
    
    # Check if interactive
    if [[ ! -t 0 ]]; then
        die "configure requires an interactive terminal"
    fi
    
    # Load existing config or use defaults
    load_config "$config_file"
    
    # Run menu
    menu_main
    
    echo ""
    log_success "Configuration complete"
}
